version: "3.1"
services:
  db:
    image: mysql:5.7.22
    tty: true
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  default:
    external:
      name: dev