server:
  address: 0.0.0.0
  port: 8080


app:
  WORKSPACE_ID: ${WATSON_CONVERSATION_WORKSPACE_ID:none}
  WATSON_USERNAME: ${WATSON_CONVERSATION_USERNAME:none}
  WATSON_PASSWORD: ${WATSON_CONVERSATION_PASSWORD:none}